version: '2'

services:
    web:
        build: .
        ports: 
            - "8000:80"
        depends_on:
            - db
        environment:
            DatabaseServer: "db"
            DatabaseName: "mydb"
            DatabaseUser: "sa"
            DatabaseUserPassword: "SA_PASSWORD=PASSWORD@123"
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: "PASSWORD@123"
            ACCEPT_EULA: "Y"